
  - name: Ldap Sync CronJob
    when: WITH_LDAP is defined and WITH_LDAP|bool == true
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: api-ldap-sync-full-cronjob.yml.j2

  - name: Ldap Worker Deployment
    when: WITH_LDAP is defined and WITH_LDAP|bool == true
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      namespace: "{{ NAMESPACE }}"
      template: api-ldap-worker-deployment.yml.j2

  - name: Delete Ldap Sync CronJob
    when: WITH_LDAP is not defined or WITH_LDAP|bool == false
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      namespace: "{{ NAMESPACE }}"
      resource_definition:
        apiVersion: batch/v1beta1
        kind: CronJob
        metadata:
          name: api-ldapsync-full-cronjob
          namespace: "{{ NAMESPACE }}"

  - name: Delete Ldap Worker Deployment
    when: WITH_LDAP is not defined or WITH_LDAP|bool == false
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      namespace: "{{ NAMESPACE }}"
      resource_definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: api-worker-deployment
          namespace: "{{ NAMESPACE }}"

  - name: Delete legacy ldapsync deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      namespace: "{{ NAMESPACE }}"
      resource_definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: api-ldapsync-deployment
          namespace: "{{ NAMESPACE }}"

  - name: Delete legacy ldapsync service
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      namespace: "{{ NAMESPACE }}"
      resource_definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: api-ldapsync-svc
          namespace: "{{ NAMESPACE }}"
