galaxy_info:
  role_name: fwu
  author: Schul-Cloud Verbund
  description: s3 gateway to FWU content
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
