API_H5P_EDITOR_MEMORY_LIMIT: "8Gi"
API_H5P_EDITOR_MEMORY_REQUEST: "2Gi"

# H5P Consumer defaults
API_H5P_CONSUMER_MEMORY_LIMIT: "2Gi"
API_H5P_CONSUMER_MEMORY_REQUEST: "512Mi"
API_H5P_CONSUMER_CPU_LIMITS: "1000m"
API_H5P_CONSUMER_CPU_REQUESTS: "100m"
API_H5P_CONSUMER_REPLICAS: 1
