WITH_MIGRATION_SYSTEMS: false
API_MIGRATION_SYSTEMS_REPLICAS: 1
API_MIGRATION_SYSTEMS_CPU_LIMITS: 2000m
API_MIGRATION_SYSTEMS_CPU_REQUESTS: 100m
API_MIGRATION_SYSTEMS_MEMORY_LIMITS: 2Gi
API_MIGRATION_SYSTEMS_MEMORY_REQUESTS: 150Mi