# https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md
apiVersion: networking.k8s.io/v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: staging-ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
  spec:
#    tls:
#    - hosts:
#      - $HOSTNAME
#      secretName: wildcard-domain-io
    rules:
    - host: $HOSTNAME
      http:
        paths:
        - backend:
            serviceName: $SERVICE_NAME
            servicePort: 80
          path: /