galaxy_info:
  role_name: schulcloud-server-migration-system
  author: Schul-Cloud Verbund
  description: role for separation of user system migration at the schulcloud-server
  company: Schul-Cloud Verbund
  license: license (AGPLv3)
  min_ansible_version: 2.8
  galaxy_tags: []
dependencies: []
