name: Test e2e

on:
  pull_request:
    branches:
      - main
    types: [labeled, synchronize]
  workflow_dispatch:
    label:
      name: 'run tests'

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    # run the action, when label 'run tests' has been set or is present at the commit time 
    if: "contains( github.event.label.name , 'run tests' ) || contains( github.event.pull_request.labels.*.name , 'run tests' )"
    steps:
      - uses: actions/checkout@v2
      - name: show env
        run: | 
          echo $env
      - name: run git change
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"
      - name: execute tests
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          MY_DOCKER_PASSWORD: ${{ secrets.MY_DOCKER_PASSWORD }}
        run: curl "https://raw.githubusercontent.com/hpi-schul-cloud/end-to-end-tests/main/scripts/ci/fetch.github.sh" | bash
      - uses: actions/upload-artifact@v2
        name: upload results
        if: always()
        with:
          name: report
          path: end-to-end-tests/reports
